#pragma once
#include <cstdint>
#include "body_art.h"

// The fish's body, one character per pixel and one pixel per world cell, read
// by body_art's rules for the reasons enemy_art.h gives for keeping a body's art
// in src/physics/ at all.
//
// A largemouth bass on a man's legs, nose tilted up, with a man's arm growing out
// of the top of its head: up, over the snout, and down to a hand hanging limp at
// the wrist in front of the mouth -- the anglerfish's lure, if the lure were a
// hand. 94x84, the troll's 70 rows plus a fifth: from the elbow's crown to the
// soles it stands 80 cells against the troll's 66.
//
// Drawn the way the player's owl is rather than the way the troll is: no
// outline, three or four tones a material, and the form carried by where one
// tone meets the next. Generated by tools/fish_art.py from shapes, for the
// troll's reason (troll_art.h); regenerate with `python tools/fish_art.py` and
// paste the rows over ROWS below. The static_asserts at the bottom decide whether
// the result is still a body.
//
// The roles:
//  - 'E' and 'O', the eye, are the HEAD. Four across, so one arrow's bite
//    (radius 2) through the pupil leaves a rim of it: two good shots, as for the
//    troll's two eyes, rather than one lucky one.
//  - 'a' to 'g', the middle of the flank, are the HEART and the root of the
//    severing fill.
//  - 'p' 'q' 'r' 's', the arm, are the ARM by letter (body_art::Art::arm),
//    because no column rule can say which of the pixels above and in front of
//    the head are arm. It joins the head only within a few cells of the
//    shoulder -- checked below -- so a shot through the shoulder takes the whole
//    arm off, and the hand hanging by the lip never fuses to it.
//  - The legs are geometry, as for every body: inside the box's columns from
//    Species::rig.hip_row down. Nothing else of the fish is there -- the fins
//    that hang below the belly are outside the box -- and the two columns either
//    side of the leg split are empty, so a leg hangs from its hip alone.
namespace fish_art {

inline constexpr int W = 94;
inline constexpr int H = 84;

inline constexpr const char* ROWS[H] = {
    "............................................................................................."
    ".",
    "............................................................................................."
    ".",
    "............................................................................................."
    ".",
    "............................................................................................."
    ".",
    "............................................................................................."
    ".",
    "......................................................................rr....................."
    ".",
    ".....................................................................rrrqq..................."
    ".",
    "....................................................................rrrrqqq.................."
    ".",
    "...................................................................rrrrqqppp................."
    ".",
    "...................................................................rrqqqqqppp................"
    ".",
    "..................................................................rrqppqqqqppp..............."
    ".",
    ".................................................................rrqqpssqqqqppp.............."
    ".",
    "................................................................rrqqpps..qqqqppp............."
    ".",
    "................................................................rrqppss...qqqqppp............"
    ".",
    "...............................................................rrqqpss.....pqqqppp..........."
    ".",
    "..............................................................rrrqpss........qqqqppq........."
    ".",
    ".............................................................rrrqqpss.........pqqqppp........"
    ".",
    "...........................................................rrrrqqpss............qqqpps......."
    ".",
    "............................................B..B..B..B..B.rrrrrqppss.............qqqpps......"
    ".",
    "......................................B..B..B..B..B..B..B.rrrqqqpss................rqpp......"
    ".",
    "..............................HIH.....B.HBHHBHHBHHBHHBHHB.rrqqppss..................rqps....."
    ".",
    "............................HIHIHIHIH.BHHBHHBHHBHHBHHBHBBBrrqpppss..................rqqps...."
    ".",
    "..........................HIHIHIHIHIH.BHHBHHBHHBHBBBBBBBBBrrqppss...................rrqpss..."
    ".",
    ".........................IHIHIHIHIHIHIBHHBHBBBAAAAAAAAAAAAAAAAps....................rrqpps..."
    ".",
    ".........................IHIHIHIIHIHIHIBBBAAAAAAAAAAAAAAAAAAAA...AAAAAA.............rrqpps..."
    ".",
    ".........................HIHIHIHIHIHIHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...........rrqpsss.."
    ".",
    ".........................HIHIHIHIHIHAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAA..........rrqps.s.."
    ".",
    ".........................HIHIHIHIHAAAAAAAAAAAAAABBBBBBBBBBBBBBAABDDDDBBAAAA.........rqqps...."
    ".",
    ".........................HIHIHIHAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBDBEEBDBBBAAA........rq.ps...."
    ".",
    "........................IHIHI.AAAAAABABBBBBBBBBBBBBBBBBBBBBBBBBBBEOOEBBBBBAAA.......rq.pps..."
    ".",
    ".II.....................IHI..ABAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEOOEBBBBBBAA.......rq.p.s..."
    ".",
    "BBII.......................AABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDEEBDDBBBBBBA.......q.p.p..."
    ".",
    "BBIIIH....................ABABBBBBBBBBBBBBBBBBBbbbbBBBBBBBBDDDBDDDDDDDDDDDDBBA.......q.p.p..."
    ".",
    "BBHIIIH..................ABBBBBBBBBBBBBBBBBBbbccccccccCCCCBDDDDDDDDDDDDDDDDDDBA........p....."
    ".",
    ".BHHHIIIH...............ABBBBBBBBBBBBBBBBBcccccccccccccAAABDDDDDDDDDDDDDDDDDDMM.............."
    ".",
    ".BIHHHIIIH..............BBBBBBBBBBBBCCCCBccccbccccacccaaAABAADDDDDDDDDDDDMMMMFF.............."
    ".",
    ".BIIIHHHIIHI..........AABBBBBBBBCCCCCCCCcccaaacccaaaaabaAABBBDDDDDDDMMMMMFFFFDD.............."
    ".",
    "..BIIIIHHIIHI.......AABABBBCBCCCCCCCCAAaccaaaabaababaaabaABBBDDDMMMMMFFFFGGGGGF.............."
    ".",
    "..BHHIIIHHHIHI...AAABABBBCCCCCCCCCCCCAAaaabaaababHIHbbbbdDDBDMMMFFFFFGGGGGGGGF..............."
    ".",
    "...HHHHHIIHHIHIAABBBBBBBCAAACCCAAAAAABAababbbbbbIHIHIHIHIDDDBGDFGGGGGGGGGGGGF................"
    ".",
    "...IIIIHHHIIAAABBBBBAACBCAABBBAABBBABABbabbddcdIHIRRRQQIHIGGBGGGGGGGGGGGGGFF................."
    ".",
    "....IIIIIIHABBBBBBBAAAAAABBBABBBBDBBBBDdddddddHIHRRRQQPPHIGGGBGGGGGGGFFGFFF.................."
    ".",
    "....HHHHHHHBCAAAAAABAABABABBBBBBDDDBBDDDddgggggIRRRRQQPPSIGGGBBGGFFFFFFFFF..................."
    ".",
    ".....IIIIIIDCAAABAABBBDBBBGGGBBGGGGGGGGGGGgggggRRRRQQQPPSSGGGGBGGFFFFFFFF...................."
    ".",
    ".....HHHHHHGGDABBBBBDDGGGGGGGGGGGGGGGGGGGGGGGggRRRQQQQPSSSGGFFGBFIIHIHFF....................."
    ".",
    "......HHHHHFGGDGGBBGGGGGGGGFGGGGGGGGGGGGGGGGGGGRRRQQQQPSSSFFFFFFFHIHIH......................."
    ".",
    "......HHHIIFFFGGGGGGGGGGFFFFFFGGGGGGGGGGGGGGGGGRRRQQQPPSSSFFFFFFFFIHIH......................."
    ".",
    "......IIIHHIFFFFFFFFFFFFFFFFFFFFFFFFFGGGGGFFFFFRRRQQPQPSSSFFFFFFF.IHIH......................."
    ".",
    "......IHHIIHHIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRQQQPPSSSFFFFF...IHIH......................."
    ".",
    "......HHIIHHIHIHH.........HIFFFFFFFFFFFFFFFFFFFFRRQQPQPSSSFF.......HIH......................."
    ".",
    "......IIIHHIHIHI...........IHIFFFFFFFFFFFFFFFFFFRRQQQPPSSS.........IHI......................."
    ".",
    "......IHHIIHHIH............IHIHIFFFFFFFFFFFFFFFFRRRQPQPPSS.........IHI......................."
    ".",
    ".....IHHIIHHIHI.............HIHIHIHIHFFFFFFFFFFF.RRQQPPPSS..................................."
    ".",
    ".....HHIIHHIIH..............HHIH..RQQPPSSSS......RRQQQPPSS..................................."
    ".",
    ".....BIIHHIIH...............IHIH..RQQPPPSSSS.....RRQQPQPSSS.................................."
    ".",
    ".....BIIHHII.................HIH...RQPPSSSS.......RRQQPPSSS.................................."
    ".",
    ".....BIHHIIH.................HIH...RQPPSSSS.......RRQQQPSSS.................................."
    ".",
    ".....BHHIIH........................RQPPPSSSS......RRQQPPSSS.................................."
    ".",
    ".....BHHIIH........................RQQPPSSSS......RRRQQPSSS.................................."
    ".",
    ".....BHIIH..........................QQPPSSSS.......RRQQPSSS.................................."
    ".",
    ".....BBII...........................RQPPSSSS.......RRQQPSSS.................................."
    ".",
    ".....BBIH...........................RQPPSSSS.......RRQQPSSS.................................."
    ".",
    ".....BBI............................RQQSSSSS.......RRRPPSSS.................................."
    ".",
    ".....................................RQPSSSS........RRQPSSS.................................."
    ".",
    ".....................................RQPSSSS........RRQPSSS.................................."
    ".",
    ".....................................RQPSSSS........RRQPSSS.................................."
    ".",
    "....................................RRQPSSS........RRRQSSS..................................."
    ".",
    "...................................RRQPSSSS.......RRRQPPSS..................................."
    ".",
    "...................................RQQPSSSS.......RRRQPSSS..................................."
    ".",
    "...................................RQQPSSSS.......RRRQPSSS..................................."
    ".",
    "...................................RQQPSSS........RRRPPSS...................................."
    ".",
    "...................................RQPPSSS........RRQQSSS...................................."
    ".",
    "...................................RQPSSSS........RRQPSSS...................................."
    ".",
    "....................................QQSSSS.........RQPSSS...................................."
    ".",
    ".....................................QPSSS..........RQPSS...................................."
    ".",
    ".....................................QSSS...........RPSS....................................."
    ".",
    ".....................................QPSS...........RQSS....................................."
    ".",
    ".....................................RPSS...........RQPS....................................."
    ".",
    ".....................................RQSS...........RRPS....................................."
    ".",
    ".....................................QQP............RRQ......................................"
    ".",
    "....................................RQPSS..........RRQPP....................................."
    ".",
    "....................................QQPPSSSSS......RQQQPPPPP................................."
    ".",
    "....................................QPPSSSSSSS.....RQQPPPSPPPP..............................."
    ".",
    ".....................................PPSSSSSSS......QQPPSSSSSS..............................."
    ".",
};

// Its own palette, as the troll's is: nothing in assets/palette.gpl is a bass.
// Olive on the back down to cream on the belly, the countershading a real one
// has, with the dark band of blotches along the flank that makes a largemouth
// read as one; and one skin ramp for the man, warm against the fish's greens, so
// the parts that are not fish are the first thing the eye separates out. The
// heart and the arm repeat tones under their own letters, as the troll's chest
// does.
using body_art::Ink;
inline constexpr Ink PALETTE[] = {
    {'A', 0xFF263019},  // back, darkest; the blotches
    {'B', 0xFF3B4A26},  // back; spines and seams
    {'C', 0xFF5A6A36},  // flank
    {'D', 0xFF828C4C},  // flank, lit; the cheek
    {'G', 0xFFC8C196},  // belly
    {'F', 0xFF9E9A72},  // belly in its own shadow; the lip
    {'H', 0xFF6A6A3C},  // fin
    {'I', 0xFF9A955E},  // fin, between the rays
    {'M', 0xFF1C1810},  // the line of the mouth
    {'a', 0xFF263019},  // flank -- HEART
    {'b', 0xFF3B4A26},  // flank -- HEART
    {'c', 0xFF5A6A36},  // flank -- HEART
    {'d', 0xFF828C4C},  // flank -- HEART
    {'g', 0xFFC8C196},  // belly -- HEART
    {'f', 0xFF9E9A72},  // belly -- HEART
    {'E', 0xFFC4502A},  // the eye's red ring -- HEAD
    {'O', 0xFF120E0A},  // the pupil -- HEAD
    {'S', 0xFF6E5444},  // skin, shadow
    {'P', 0xFF9A7B62},  // skin, mid
    {'Q', 0xFFC2A384},  // skin, lit
    {'R', 0xFFDEC6A4},  // skin, highlight
    {'s', 0xFF6E5444},  // arm, shadow -- ARM
    {'p', 0xFF9A7B62},  // arm, mid -- ARM
    {'q', 0xFFC2A384},  // arm, lit -- ARM
    {'r', 0xFFDEC6A4},  // arm, highlight -- ARM
};
inline constexpr int PALETTE_COUNT = static_cast<int>(sizeof(PALETTE) / sizeof(PALETTE[0]));

inline constexpr int FOOT_ROWS = 3;
// The arm is lettered, so every row may hold it.
inline constexpr int ARM_TOP = 0;
// The box is the fish's middle and the legs: 30 columns, centred. species::FISH
// checks it against its own box width.
inline constexpr int BOX_LEFT = 32;
inline constexpr int BOX_RIGHT = W - BOX_LEFT;
// Where the arm turns: the top of the head, where it grows out. species::FISH's
// rig turns the arm about this same point, and says so with a static_assert.
inline constexpr int SHOULDER_X = 60;
inline constexpr int SHOULDER_Y = 22;
// The rows inside the box from which a pixel is leg, and the column the rear leg
// ends before; the rig's hip_row and leg_split, stated here so the checks below
// can read them.
inline constexpr int HIP_ROW = 53;
inline constexpr int LEG_SPLIT = 47;

inline constexpr body_art::Art ART = body_art::with_arm_box(body_art::Art{
    ROWS, W, H, PALETTE, PALETTE_COUNT, "EO", "abcdfg", BOX_LEFT, ARM_TOP, FOOT_ROWS, "pqrs"});

static_assert(body_art::well_formed(ART),
              "fish_art::ROWS has a row of the wrong width or a character with no "
              "PALETTE entry");
static_assert(body_art::count_where(ART, &body_art::Art::is_head) >= 9 &&
                  body_art::count_where(ART, &body_art::Art::is_heart) > 0,
              "the fish needs its whole eye ('E'/'O') and a heart ('a'-'g'), or it "
              "is born dead -- or dies to one arrow in the eye");
static_assert(body_art::count_where(ART, &body_art::Art::is_foot) > 0,
              "the fish has nothing in its FOOT_ROWS inside the box, so it is born "
              "footless and collapses on its first hit");
static_assert(body_art::count_where(ART, &body_art::Art::is_arm) > 0,
              "the fish has no arm letters ('p'-'s'), so it is born armless and "
              "can never cast");
static_assert(body_art::connected<W * H>(ART),
              "some fish pixel is not 8-connected to the heart; it would fall off "
              "as sand the first time the fish is hit anywhere");
static_assert(body_art::stands_on_bottom_row(ART), "the fish art floats: its bottom row is empty");

// The arm touches the rest of the body only at its root. A pixel of it beside
// the head anywhere further out -- the hand against the lip, the forearm along
// the brow -- would hold the arm on after the shoulder was shot through.
constexpr bool arm_hangs_free() {
    for (int y = 0; y < H; ++y)
        for (int x = 0; x < W; ++x) {
            if (!ART.is_arm(x, y)) continue;
            const int sx = x - SHOULDER_X, sy = y - SHOULDER_Y;
            if (sx * sx + sy * sy <= 9) continue;
            for (int dy = -1; dy <= 1; ++dy)
                for (int dx = -1; dx <= 1; ++dx) {
                    const int nx = x + dx, ny = y + dy;
                    if (nx < 0 || nx >= W || ny < 0 || ny >= H) continue;
                    if (ART.is_body(nx, ny) && !ART.is_arm(nx, ny)) return false;
                }
        }
    return true;
}
static_assert(arm_hangs_free(),
              "a fish pixel touches the arm away from the shoulder, so the arm can "
              "no longer be shot off at the shoulder");

// The legs hang from the hips alone: the columns either side of the split are
// empty from the hips down, and the rows above the hips inside the box -- the
// belly -- are where each joins the body.
constexpr bool legs_hang_free() {
    for (int y = HIP_ROW; y < H; ++y)
        if (ART.is_body(LEG_SPLIT - 1, y) || ART.is_body(LEG_SPLIT, y)) return false;
    return true;
}
static_assert(legs_hang_free(),
              "a fish pixel fills the gap between the legs, so neither leg can be "
              "severed at the hip on its own");

inline constexpr int PIXEL_COUNT = body_art::count_where(ART, &body_art::Art::is_body);

}  // namespace fish_art
