#pragma once
#include <cstdint>
#include "body_art.h"

// The troll's body, one character per pixel and one pixel per world cell, read
// by the same rules as the ghoul's (body_art.h) for the reasons enemy_art.h
// gives for keeping a body's art in src/physics/ at all.
//
// After the trolls of Elden Ring: a hunched giant with a small head sunk
// forward off a mass of back and shoulder, arms long enough that the fists hang
// below the knees, iron shackles still on its wrists and neck, and a club in the
// leading hand. 52x70 against the player's 14x26 frame -- a body nearly three
// times the player's height, which is the whole of "imposing" at four screen
// pixels per cell.
//
// Generated by tools/troll_art.py from shapes, because at this size the shading
// is a function of the shapes and hand-typing 3,640 characters makes every edit
// a re-shade. Regenerate with `python tools/troll_art.py` and paste the rows over
// ROWS below; the static_asserts at the bottom are what decide whether the
// result is still a body.
//
// The roles, as for the ghoul:
//  - 'E', the eyes, are the HEAD. Their inner pixels are five cells apart, so
//    one arrow's bite (radius 2) never reaches both: a head kill is one
//    well-placed shot per eye, not one shot between them as for the ghoul. A
//    body this size should not drop to a single lucky arrow.
//  - 'h', 'j' and 'k', the middle of the chest, are the HEART and the root of
//    the severing fill.
//  - Arms are everything outside the box's columns from ARM_TOP down; feet are
//    what is inside them in the bottom FOOT_ROWS rows.
//
// The empty column each side of the torso from ARM_TOP down, and the four empty
// columns between the legs below the loincloth, are load-bearing exactly as the
// ghoul's gaps are: an arm hangs from the shoulder alone and a leg from the hip
// alone, so cutting through the shoulder brings the whole arm down. The
// difference is thickness. A troll's arm is eight cells across against an
// arrow's five-cell bite, so a limb does not come off to one arrow -- it is
// chipped, and comes off to the second or third in the same place. That is the
// local part of "comes apart where it is hit" at this size.
namespace troll_art {

inline constexpr int W = 52;
inline constexpr int H = 70;

inline constexpr const char* ROWS[H] = {
    "....................................................",
    "....................................................",
    "....................................................",
    "....................................................",
    "...................KKKKKKKKKKKKKK...................",
    "................KKKRRYYYYYYYYYYYZKKK................",
    "..............KKRRRRYYYYYYYYYYYZZYYZKK..............",
    ".............KRRRRQYYYYZZYYYYZZZYYZZZPK.............",
    "............KRRRQQQYYYZZZZZZZZZZYYZZZSPK............",
    "...........KRRRQQQQYYZZZZZZZZZZZZYZZZSPPK...........",
    "..........KRRRQQQQQYYZZRZZZZZZZZSYZZZSQPPK..........",
    "..........KRRRQQQQQYYZZSSSSSSSSSSYYZZPPPSK..........",
    ".........KRRRQQQQQQYYZZSEESSSSEESYYZZSQPPSK.........",
    ".........KRQQQQQQQQYYZZQRRRQQQQQPYYZZPPPPRK.........",
    ".......KKRRQRQPQQQQYYZZRRRQRRQQPPYYZZSRRRRQKK.......",
    "......KRRRRRQQPPQQQYYZRQRRRSSRSPPSYZZQRRRQQQPK......",
    ".....KRRRQRQQPPPPQQYYZRRTRRRRQQTPSYZZQRRQQQQPPK.....",
    "....KRRRQRQQQQPPSPQYYZRRTRQRQQQTPPYZZQRQQQQQPPSK....",
    "....KRRRRQQQQPPSSSQYYZQZZZZZZZZZZSYZZQQQQQQPPSSK....",
    "....KRRRQQQQQPPSSPQYYZQRQQQQPPPPSSYZZPQQQQPPPPSK....",
    "....KRRQQQQQPPPSSSQYYZPQJJJJJJJSSSYZZPQQQPPPPSSK....",
    "....KRRQQQQPPPPSSSYYZZIJJJJJJJJJJJYZZZSPPPPPSSSK....",
    ".....KRQQPPPPPSKSSIYZIIJJJJJJIIIIIIZKPPPPPPSSSSK....",
    ".....KQQQPPPPKK.KKSIIIIIIIIIIIIIIIKK.KKPPPSSSSSK....",
    ".....KQQPPPSK.....KQQQPPIIIIIIIPPK.....KPSSSSSSK....",
    ".....KRQPSPSK....KRRRQQQPPPPPPPPQPK.....KSPPSSSK....",
    ".....KRRQPSSK...KRRRQQQjjjjjjQQQQPPK....KQPQPSSK....",
    ".....KRRQPPSK..KRRRQQjjjjjjjjjjQQQPSK...KRQQPPSK....",
    ".....KRRQPSSK..KRRRQjjjjjjjjjjjjQPPSK...KRRQPSSK....",
    ".....KRRQPSSK..KRRQjjjjjjjjjjjjjjPPPK...KRQQPPSK....",
    ".....KRRQPSK...KRRQjjjjjjjjjjjjjjPPSK....KRQPSSK....",
    ".....KRRQPSK..KRRRQjjjjjjjjjjjjjjPPSSK...KRQPPSK....",
    ".....KRRQPSK...KRRjjjjjjjjjjjjjjhhPSK....KRQPSSK....",
    ".....KRRQPSK...KRRQjjjjjjjjjjjkhhPPSK....KRRPPSK....",
    ".....KRRQPSK...KRQQjjjjjjkkjjjjjjSSSK....KRQQSSK....",
    ".....KRRQQSK...KRRQjjjjjjjjjjjjjjPSSK....KRRQQSK....",
    ".....KRRQPPK....KRSSkkkkjjjjkkkkSSPK.....KRRQPPK....",
    ".....KRRQPPK.....KRRRjjjjjjjhjhQPPPK.....KRRQPSK....",
    ".....KRRQPSK....KRRRQQQjjhjhjPQPQPPSK....KRRQPSK....",
    ".....KRRQPSK....KRRQQQQQPQPQPQPQPPSSK....KRQQPSK....",
    ".....KRQQPSK....KRRQQQQPQPQPQPQPQPPSK....KRQPPSK....",
    ".....KRRQPSK...KRRQQQQPQPQPQPQPQPPPSSK...KRQPSSK....",
    ".....KRQQPPSK...KRRQQPQPQPSPQPQPPPPSK...KRRQPSSK....",
    ".....KRRQPSSK...KRQQPQPQPQPQPQPPPPSSK...KRRQPSSK....",
    ".....KRQQPPSK...KRQQQPQPQPQPQPPPPSSSK...KRQQPSSK....",
    "....KJJJJJJIK..KJJJJJJJJJJJJJJJJJJJJK..KJJJJJJJIK...",
    "....KJJJJJIIK..KJJJJJJJJJJJJJJJJJIIIK..KJJJJJJIIK...",
    "....KJJIIIIIK..KNNLLLLLLLLLLLLLLLLLLK..KJJIIIIIIK...",
    "....KJIIIIIIK..KNNNNNNNNNNNNNNNNNNLLK..KJIIIIIIIK...",
    ".....KQPPSSSK..KNNNNNNNNNNNNNNNNNLLLK...KQPPSSSK....",
    ".....KRQQPPSK..KNNLLLLLLLLLLLLLLLLLLK...KRQPPSSK....",
    ".....KRQQPSSK..KNNLLLLLLLLLLLLLLLLLLK...KRQQSSSK....",
    ".....KRRRRQSK..KNLLLLLLLLLLLLLLLLLLLK...KQRRQQSK....",
    ".....KRRRQQPK..KQPPSSNNNNNNNNLLSSSSSK...KRRRQPPSK...",
    ".....KRRRQQPK..KRQQQPNNNNNNLLLLSPPSSK...KRRRQPPSWK..",
    ".....KRRQQPPK..KRQQPPNNLLLLLLLLSPPSSK...KRRQQPSSWK..",
    ".....KRRQPPSK..KRQQPPNNLKKKKLLLSPPSSK...KRQQPPSSWK..",
    ".....KRRQPPSK..KRQQPPSSK....KPPSPPSSK...KRQQPSSSWK..",
    ".....KSQSPSSK..KRQQPPSSK....KRQQPPSSK...KSQSPSSSWK..",
    "......KQPPSK...KRPPPPSSK....KRQPPPSSK....KQPPSSWWWK.",
    ".......KKKK....KRQQPPSSK....KRQQPPSSK.....KKKSXWXWK.",
    "...............KRQQPPSSK.....KQQPPSSK........KJXXWK.",
    "...............KRQQPPSSK.....KQQPPSSK........KXXWWK.",
    "...............KRQPPSSSK.....KRQPSSSK........KXXXJK.",
    "...............KRQPPPSSK.....KQQPSSSK........KXXXWK.",
    "................KRQQPPK......KRRQQPPK........KJXWWK.",
    "...............KRQQPPSK......KQQQPPSK.......KXXXWWWK",
    "..............KQQQPPPSSK....KQQPPPSSSK......KXXXWJWK",
    "...............KQPPSSSK......KQPPSSSK........KXXWWK.",
    "................KKKKKK........KKKKKK.........KKKKKK.",
};

// Its own palette rather than the game's: nothing in assets/palette.gpl is a
// hide. Grey-brown, warm in the light and cold in the shade, so it reads as
// skin against both the forest's greens and the cave's greys, and the sand it
// leaves behind is visibly its flesh, not the Sand row's yellow.
using body_art::Ink;
inline constexpr Ink PALETTE[] = {
    {'K', 0xFF15110F},  // outline
    {'S', 0xFF3E3430},  // hide, shadow
    {'P', 0xFF5E5049},  // hide, mid
    {'Q', 0xFF7E6C5F},  // hide, lit
    {'R', 0xFF9C8875},  // hide, highlight
    {'k', 0xFF3E3430},  // chest, shadow -- HEART
    {'h', 0xFF5E5049},  // chest, mid -- HEART
    {'j', 0xFF7E6C5F},  // chest, lit -- HEART
    {'Z', 0xFF1B1716},  // hair
    {'Y', 0xFF332C28},  // hair, lit
    {'I', 0xFF3B3E44},  // iron
    {'J', 0xFF6E747C},  // iron, lit; also the club's studs
    {'L', 0xFF4A3322},  // loincloth
    {'N', 0xFF6B4A2F},  // loincloth, lit
    {'W', 0xFF4E3720},  // club
    {'X', 0xFF74552F},  // club, lit
    {'T', 0xFFDDD2B4},  // tusks
    {'E', 0xFFFF7A2E},  // eyes -- HEAD
};
inline constexpr int PALETTE_COUNT = static_cast<int>(sizeof(PALETTE) / sizeof(PALETTE[0]));

inline constexpr int FOOT_ROWS = 3;
inline constexpr int ARM_TOP = 24;
// The box is the torso and legs: 24 columns, centred. species::TROLL checks it
// against its own box width.
inline constexpr int BOX_LEFT = 14;
inline constexpr int BOX_RIGHT = W - BOX_LEFT;

inline constexpr body_art::Art ART{ROWS, W,     H,        PALETTE, PALETTE_COUNT,
                                   "E",  "hjk", BOX_LEFT, ARM_TOP, FOOT_ROWS};

static_assert(body_art::well_formed(ART),
              "troll_art::ROWS has a row of the wrong width or a character with no "
              "PALETTE entry");
static_assert(body_art::count_where(ART, &body_art::Art::is_head) >= 2 &&
                  body_art::count_where(ART, &body_art::Art::is_heart) > 0,
              "the troll needs its eyes ('E') and a heart ('h'/'j'/'k'), or it is "
              "born dead");
static_assert(body_art::count_where(ART, &body_art::Art::is_foot) > 0,
              "the troll has nothing in its FOOT_ROWS inside the box, so it is born "
              "footless and collapses on its first hit");
static_assert(body_art::count_where(ART, &body_art::Art::is_arm) > 0,
              "the troll has no pixels outside the box below ARM_TOP, so it is born "
              "armless and can never slam");
static_assert(body_art::connected<W * H>(ART),
              "some troll pixel is not 8-connected to the heart; it would fall off "
              "as sand the first time the troll is hit anywhere");
static_assert(body_art::stands_on_bottom_row(ART), "the troll art floats: its bottom row is empty");

// The gaps that let a limb come off, checked rather than trusted: a pixel in
// either gap column below ARM_TOP joins an arm to the ribs down its length, and
// a shot through the shoulder would take a bite and leave the arm on.
constexpr bool arms_hang_free() {
    for (int y = ARM_TOP; y < H; ++y)
        if (ART.is_body(BOX_LEFT - 1, y) || ART.is_body(BOX_RIGHT, y)) return false;
    return true;
}
static_assert(arms_hang_free(),
              "a troll pixel fills the gap column between an arm and the torso, so "
              "that arm can no longer be severed at the shoulder");

inline constexpr int PIXEL_COUNT = body_art::count_where(ART, &body_art::Art::is_body);

}  // namespace troll_art
