#pragma once

#include "render/depth_rig.h"

// Backdrop sets drawn by the perspective rig. render/depth_rig.h is the argument;
// this is the data.
//
// Separate from bg1::SETS rather than a fifth row in it, and that is not
// duplication. Every check boot_test runs over bg1::SETS is a property of the
// banded, vertically-locked, world-sized model -- exactly one banded layer, every
// factor capped at 1.00, the ground cut on flat paint -- and a rig set is the
// opposite on each count. Folding it in would mean teaching those checks
// exceptions; a separate table gets its own checks in rig_test instead, and
// leaves the four existing sets drawing exactly as they did.
//
// Like bg1_backdrop.h this knows no SDL, so rig_test can include it and check
// every number here against the BMP it describes.
namespace rig_backdrop {

// One layer.
//
// `foot_row` is the layer's depth, stated the way the art states it: the row its
// lowest painted pixel stands on. The factor is depth_rig::factor_at of that row
// and is never written down. -1 means the layer does not stand on the ground --
// sky, clouds, the sun's reflection -- and then `factor` is used instead.
//
// `line_scroll` marks the ground plane: drawn one row at a time, each at
// depth_rig::plane_factor of its own row, horizontally and vertically.
//
// `ripple_row0/1` (half-open, art rows) are rows that shimmer sideways with time.
// A rippled layer is drawn per row over that range, so its paint must be inside
// it -- rig_test checks.
//
// `on_plane` is for paint that lies ON the plane without being part of it -- the
// sun's reflection. It is placed vertically by the plane's own rows, so it stays
// on the water it was painted on as the plane stretches, while its horizontal
// factor stays its own (0 for the glint, which stays under the sun). Drawn per
// row over its ripple range.
//
// `drift` is cells per second of sideways motion with no camera motion at all,
// for the clouds. Render-only, like the ripple: both read the wall clock, and
// neither can reach the simulation, because nothing in src/physics/ can include
// a render header.
struct Layer {
    const char* file;
    int foot_row;
    float factor;  // only when foot_row < 0
    bool opaque;
    bool line_scroll;
    bool is_foreground;
    bool on_plane;
    int ripple_row0, ripple_row1;
    float drift;
};

struct Set {
    const char* scene;  // the assets/scenes.txt row this backs
    const char* dir;
    int native_w, native_h;
    depth_rig::Rig rig;
    float ripple_amplitude;  // cells
    const Layer* layers;
    int layer_count;
};

// --- bg_tarn: a mountain lake at golden hour ----------------------------------
//
// Generated by `python tools/generate_bg_tarn.py`, which states the same horizon,
// contact row and feet; inspired by art_src/Background_1. The script's header
// has the art argument.
//
// The horizon is row 200 and the contact row 264, the terrain's surface. The
// eye height is therefore 64 rows, and the factors below follow from the feet:
//
//     mountains 202 -> 0.031    dunes      210 -> 0.156
//     ridge     204 -> 0.063    far pines  240 -> 0.625
//     mesas     207 -> 0.109    near pines 252 -> 0.813
//
// The empty stretch between 0.16 and 0.63 is the lake. It is the widest thing in
// the frame and the plane's line scroll is what carries it: watching the water
// shear between the far shore and the near one is most of the depth in this set.
//
// The reeds are 1.30 and in front of the player. That is above every bg1 set's
// cap of 1.00, which that cap exists for a world-sized layer that does not wrap.
// Every rig layer wraps, so the cap does not apply; 1.30 rather than more
// because the layer crosses the window 30% faster than the world does, and
// faster than that a reed is a flicker rather than a thing.
//
// vertical_strength 0.75, chosen from preview_backdrop flights at 0.5 and 0.75.
// At 0.5 the horizon falls with the camera at half the world's rate, so flying to
// the ceiling shows only sky -- the valley drops out of the window, which reads as
// the backdrop lagging rather than as height. At 1.0 the horizon stays put, which
// is honest, but the plane magnifies 1 + 164/64 = 3.6x at the ceiling (1080p) and
// the lake's rows smear. 0.75 keeps the lake in the bottom third of the window at
// the ceiling and magnifies it at most 1 + 164 * 0.75 / 64 = 2.9x, which the
// plane's undithered bands survive. TUNING.md carries it.
//
// The ripple is 0.6 cells either way: under one cell, so a water row never
// detaches from the row above it by a whole art pixel, which reads as tearing
// rather than shimmer. The clouds drift 0.6 cells/s, right to left -- a whole
// lap of the 688-cell sky takes about nineteen minutes, which is slow enough to
// be noticed rather than watched.
inline constexpr Layer TARN_LAYERS[] = {
    // file                         foot  factor opaque line   fg     plane  ripple     drift
    {"bg_tarn_11_sky.bmp",           -1, 0.00f, true,  false, false, false,   0,   0,  0.0f},
    {"bg_tarn_10_clouds.bmp",        -1, 0.01f, false, false, false, false,   0,   0, -0.6f},
    {"bg_tarn_09_plane.bmp",         -1, 0.00f, false, true,  false, false, 212, 239,  0.0f},
    {"bg_tarn_08_glint.bmp",         -1, 0.00f, false, false, false, true,  212, 239,  0.0f},
    {"bg_tarn_07_mountains.bmp",    202, 0.00f, false, false, false, false,   0,   0,  0.0f},
    {"bg_tarn_06_ridge.bmp",        204, 0.00f, false, false, false, false,   0,   0,  0.0f},
    {"bg_tarn_05_mesas.bmp",        207, 0.00f, false, false, false, false,   0,   0,  0.0f},
    {"bg_tarn_04_dunes.bmp",        210, 0.00f, false, false, false, false,   0,   0,  0.0f},
    {"bg_tarn_03_pines_far.bmp",    240, 0.00f, false, false, false, false,   0,   0,  0.0f},
    {"bg_tarn_02_pines_near.bmp",   252, 0.00f, false, false, false, false,   0,   0,  0.0f},
    {"bg_tarn_01_reeds.bmp",         -1, 1.30f, false, false, true,  false,   0,   0,  0.0f},
};

inline constexpr Set SETS[] = {
    {"bg_tarn", "assets/bg_tarn/", 688, 288, depth_rig::Rig{200, 264, 0.75f}, 0.6f,
     TARN_LAYERS, static_cast<int>(sizeof(TARN_LAYERS) / sizeof(TARN_LAYERS[0]))},
};

inline constexpr int SET_COUNT = static_cast<int>(sizeof(SETS) / sizeof(SETS[0]));

// A layer's horizontal factor: derived from its feet when it has some.
constexpr float factor_of(const Set& set, const Layer& l) {
    return l.foot_row >= 0 ? depth_rig::factor_at(set.rig, static_cast<float>(l.foot_row))
                           : l.factor;
}

// Null for a scene with no rig set, for the reason bg1::find gives.
inline const Set* find(const char* scene) {
    if (!scene) return nullptr;
    for (int i = 0; i < SET_COUNT; ++i) {
        const char* a = SETS[i].scene;
        const char* b = scene;
        while (*a && *a == *b) { ++a; ++b; }
        if (!*a && !*b) return &SETS[i];
    }
    return nullptr;
}

} // namespace rig_backdrop
