"""Exports PALETTE (tools/pixel_art.py) to assets/palette.gpl - the GIMP
palette format, also read directly by Aseprite and Krita. Tools/pixel_art.py
is the source of truth for anything built in this repo's own scripts, and
this file is what an artist can load into external editors.

Regenerate after any change to PALETTE:
    python tools/export_palette_gpl.py
"""
from pixel_art import PALETTE, asset_path

with open(asset_path('palette.gpl'), 'w', newline='\n') as f:
    f.write('GIMP Palette\n')
    f.write('Name: Toop/Xoco - Forest Quantum World\n')
    f.write('Columns: 4\n')
    f.write('#\n')
    f.write('# Generated by tools/export_palette_gpl.py - do not hand-edit.\n')
    f.write('# Source of truth is PALETTE in tools/pixel_art.py.\n')
    f.write('#\n')
    for name, (r, g, b) in PALETTE.items():
        f.write(f'{r:3d} {g:3d} {b:3d}  {name}\n')

print('wrote', asset_path('palette.gpl'))
